### ISSUE TITLE
OpenGL crash

### ISSUE THREAD

**Issue by thienhv96** [flashphoner/wcs-android-sdk-samples#16]
Hi there, I have a crash with flashphoner issue below, how can I fix it?|

I/EglBase14Impl: Using OpenGL ES version 2
W/System.err: java.lang.RuntimeException: Failed to create EGL context: 0x3003
W/System.err:     at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:282)
W/System.err:     at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:78)
W/System.err:     at org.webrtc.EglBase.createEgl14(EglBase.java:215)
W/System.err:     at org.webrtc.HardwareVideoEncoder.initEncodeInternal(HardwareVideoEncoder.java:264)
W/System.err:     at org.webrtc.HardwareVideoEncoder.initEncode(HardwareVideoEncoder.java:220)

E/rtc: #
    # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 94
    # last system error: 0
    # Check failed: !env->ExceptionCheck()
    # 
    
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5198 (EncoderQueue - ), pid 2311

**Comment by flashphoner** [comment]
Please check if the issue is reproducing with the latest Android SDK build [1.1.0.57](https://flashphoner.com/downloads/builds/flashphoner_client/wcs-android-sdk/1.1/wcs-android-sdk-1.1.0.57-4d3e44c28a593f0d7a2ccce58830d79b9b5e80ac.tar.gz) in any apk shipped in the archive (streaming-min-debug.apk, media-devices-debug.apk etc).
If yes, please provide the following:
- Android version
- device model
- application name to test

**Comment by thienhv96** [comment]
Hi. I upgraded sdk from 1.1.0.55 to 1.1.0.57.
But currently, my config is missing trustAllCertificates(boolean)

Im ussing RoomManager for manage stream
        RoomManagerOptions roomManagerOptions = new RoomManagerOptions(wcsUrl.trim(), login.trim());
        roomManagerOptions.**trustAllCertificates(true);**

How can I config it with RoomManager?

**Comment by flashphoner** [comment]
Since Android SDK build [1.1.0.56](https://flashphoner.com/downloads/builds/flashphoner_client/wcs-android-sdk/1.1/wcs-android-sdk-1.1.0.56-fe4a086461161ae807693a31ae5cfc2bede72036.tar.gz) X509TrustManager class implementation is removed fromAndroid SDK code to conform Google Play requirements.
You should either use a valid SSL certificates on the server, or add your self-signed certificate to application resources: [Recommended: Add self-signed certificate to application resources](https://docs.flashphoner.com/display/ANDROIDSDK11EN/Server+SSL+certificates+checking+while+Websocket+connection+establishing#ServerSSLcertificatescheckingwhileWebsocketconnectionestablishing-Recommended:Addself-signedcertificatetoapplicationresources)
